runtime: python39

entrypoint: gunicorn -b :$PORT library_app:app

env_variables:
  FLASK_ENV: 'production'
  GOOGLE_CLOUD_PROJECT: 'library-database-application'

instance_class: F2

handlers:
- url: /static
  static_dir: static/
- url: /.*  
  script: auto
